name: 🚀 Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🐍 Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 🔨 Install Dependencies
        run: npm install

      - name: 🏗️ Build Project
        run: npm run build

      - name: 📂 Sync to Hostinger (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: u968279674
          server: 46.202.183.110
          port: 65002
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./dist/*
          remote_path: /home/u968279674/domains/usainsomnia.com/public_html/
